version: "3"

services:
  officecafeapp:
    hostname: appserver
    build:
      context: .
    image: officecafeapp
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    volumes:
      - ./src:/home/officecafe/src
    command: >
      sh -c "./wait-for.sh officecafedb:5432 &&
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - officecafedb

  officecafedb:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=officecafedb
      - POSTGRES_USER=officecafe_user
      - POSTGRES_PASSWORD=officecafe_pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
